/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencv_my_MainActivity */

#ifndef _Included_com_example_opencv_my_MainActivity
#define _Included_com_example_opencv_my_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_opencv_my_MainActivity_REQUEST_ID_MULTIPLE_PERMISSIONS
#define com_example_opencv_my_MainActivity_REQUEST_ID_MULTIPLE_PERMISSIONS 1L
#undef com_example_opencv_my_MainActivity_PHOTO_RESULT_CODE
#define com_example_opencv_my_MainActivity_PHOTO_RESULT_CODE 100L
#undef com_example_opencv_my_MainActivity_VOICE_RESULT_CODE
#define com_example_opencv_my_MainActivity_VOICE_RESULT_CODE 101L
#undef com_example_opencv_my_MainActivity_VIDEO_RESULT_CODE
#define com_example_opencv_my_MainActivity_VIDEO_RESULT_CODE 102L
#undef com_example_opencv_my_MainActivity_REQUEST_IMAGE_CAPTURE
#define com_example_opencv_my_MainActivity_REQUEST_IMAGE_CAPTURE 1L
#undef com_example_opencv_my_MainActivity_REQUEST_IMAGE_PICK
#define com_example_opencv_my_MainActivity_REQUEST_IMAGE_PICK 2L
/*
 * Class:     com_example_opencv_my_MainActivity
 * Method:    countCardboardBoxes
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_opencv_my_1MainActivity_countCardboardBoxes
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
